server.servlet.context-path=/
spring.mvc.view.prefix=/WEB-INF/view/
spring.mvc.view.suffix=.jsp
logging.level.org.springframework.web=DEBUG
spring.datasource.url=jdbc:mysql://localhost:3306/sportsbetting_roth_bence?useLegacyDatetimeCode=false&serverTimezone=UTC
spring.datasource.username=j2ee
spring.datasource.password=j2ee